### ISSUE TITLE
Initial send of data

### ISSUE THREAD

**Issue by mohage** [mohage/Infinite-burn-barrel#7]
I noticed that when I first load the app, the initial setting are not automatically sent to Arduino. I need to actually change one of the settings for the initial send to happen. 

Can you make the app send the settings upon load. Do you think this is a good idea?

**Comment by dagostini** [comment]
Of course I can. Can you just give me the default initial values? It is a good idea :)

**Comment by dagostini** [comment]
Combustion temperature has a range of 250 to 1500. Is this right? 1500 is awfully hot :)

**Comment by dagostini** [comment]
OK, in that case the app is already sending those values, so we can close this one.
