### ISSUE TITLE
Listen

### ISSUE THREAD

**Issue by mohage** [mohage/Infinite-burn-barrel#8]
Dejan,

Can we activate Listen too. I think it can just be a field read the same way as all the fields. This way Arduino can write values to this field to spit out diagnostics things or characters. If you do this, can you give me an example of how to spit out both numbers and characters.

**Comment by dagostini** [comment]
We sure can :)

I'm finished with this, you can use it by sending a custom command to the device from the arduino. Here is one example of how to use it:

Serial3.print("lsn_"); 
Serial3.println("12.34"); // Your value goes here

If you send commands like this, the app will pick it up. You can send any value you want, the 'println' function will take care of the conversions for you.
