### ISSUE TITLE
Sliders in IOS app

### ISSUE THREAD

**Issue by mohage** [mohage/Infinite-burn-barrel#9]
Dejan,

When using the sliders in the app, i notice that it's hard to, say set it to 500 exactly. What would help would be to have the setting value change as you are still using the slider and before you release the finger... Let me know if that can work?

**Comment by dagostini** [comment]
Yeah, it can be done like that, no worries. I'll have to customise the control a bit because the original control is sending constant value changes to Arduino as you drag your finger.

**Comment by dagostini** [comment]
Done 😄
